\documentclass[12pt]{article}
\usepackage{enumitem}
\usepackage{forest}
\forestset{qtree/.style={for tree={parent anchor=south, %ajoute des retour de ligne dans les arbres
	child anchor=north,align=center,inner sep=0pt}}}

\usepackage{geometry}
\geometry{
	a4paper,
	left=10mm,
	top=20mm,
  right=10mm,
  bottom=20mm,
}

\author{Billy Bouchard}
\title{GCC documentation}
\date{\today}

\begin{document}
\maketitle
\tableofcontents
\newpage
\section{Basic Variable}
\subsection{Creating a Variable}
a variable can be anything
\subsubsection{Direct Creation}
Use : \\
\verb|<VarName> = <Variable>|\\
ex : \\
\verb|HELLO = ../include}|

\subsubsection{Multiple Direct Creation}
Spacing each Var makes a List : \\
\verb|<VarListName> = <Var1> <Var2> <Var3>| \\
\verb|helloList = hello3.c hello2.c hello.c |

\subsubsection{Suffixe Creation}
using wildcard operator helps a lot:\\
\verb|<VarListName> = $(wildcard *<extension>)| \\
\verb|hellolist = $(wildcard *.c)|

\subsubsection{Copy and Replace Creation}
You can copy any variable and replace it using the special command :
\verb|<NewVarListName> = $(<VarListName>:.<CurrentExt>=.<WantedExt>)|\\
ex: \\
\verb|helloList2 = $(helloList:.c=.o)|
\newpage
\subsection{Target Condition}
\subsubsection{Target Condition type}
there is 2 target condition type :
\begin{enumerate}
  \item another target to be done prior to the one there
  \item a file
\end{enumerate}
\subsubsection{Target-file condition}
direct file is simple as putting file name: \\
\verb|<target>:<filename>|\\
\verb|single:  hello.c|
\subsubsection{file-file condition}
you can put a file name as a target:\\
\verb|<filename1>:<filename2>|\\
\verb|hello.o: hello.c|
\subsubsection{files-files condition}
you can put a lot of files by using \% operator:\\
\verb|%<filesExtension>:%<filesExtension>|\\
\verb|%.o:%.c|\\
this will create n times the file-file condition!!!

\subsection{Shortcuts}
\begin{tabular}{|l|l|l|}
  \hline
  shortcut                & value     & example                                                      \\
  \hline
  \verb|$@| & target    & f.txt: a.txt b.txt c.txt                                     \\
                          &           & echo \verb|$@| $\rightarrow$ f.txt             \\ \hline
  \verb|$<| & first arg & f.txt: a.txt b.txt c.txt                                     \\
                          &           & echo \verb|$<| $\rightarrow$ a.txt             \\ \hline
  \verb|$^| & all arg   & f.txt: a.txt b.txt c.txt                                     \\
                          &           & echo \verb|$^| $\rightarrow$ a.txt b.txt c.txt \\ \hline
\end{tabular}



\end{document}
